name: Prod deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  prod-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Install libvirt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config
      - name: Download dependencies
        run: go mod download
      - name: Build
        run: go build ./...
      - name: Run tests
        run: go test ./... -v

  prod-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: prod-test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: qarani/fargate-server:prod

  prod-deploy:
    needs: prod-build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Tailscale.
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Deploy to Prod via SSH over Tailscale....
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker network create aws-prod-network || true
            docker pull qarani/fargate-server:prod
            docker stop fargate-server-prod || true
            docker service rm fargate-server-prod || true
            docker service create \
              --name fargate-server-prod \
              --network aws-prod-network \
              --publish published=8086,target=8086 \
              --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
              --env APP_PROFILE=prod \
              --env SERVER_PORT=8086 \
              --env DOCS_PATH=/app/docs \
              --env NATS_URL=nats://nats-prod:4222 \
              --env NATS_USERNAME=nats-prod-user \
              --env NATS_PASSWORD=nats-prod-password \
              --env NATS_PREFIX=prod.v1 \
              --env EUREKA_SERVER_URL=http://discovery-server-prod:8761/eureka \
              --env EUREKA_HOSTNAME=fargate-server-prod \
              --env EUREKA_IP_ADDR=fargate-server-prod \
              --env EUREKA_INSTANCE_ID=fargate-server-prod:8080 \
              --env EUREKA_VIP_ADDRESS=fargate-server \
              qarani/fargate-server:prod



